### ISSUE TITLE
Access to Thesis

### ISSUE THREAD

**Issue by 1cookspe** [Jcparkyn/dpoint#3]
First off, great work and thank you for publishing your code!

In the README, you mention that you haven't published the full thesis online. I was wondering if the thesis is now available, or if you would know when it might be available online.

Thank you!

**Comment by Jcparkyn** [comment]
I still haven't gotten around to making it public yet (distracted with other stuff), but if you send me an email to jcparkyn(at)gmail.com I can email it to you.
